# 使用购买GPU

**分类:** 高级主题

**🎯 让我们从实际问题出发**

---


## 💭 开始之前:想想这个问题

学习 **使用购买GPU** 能帮我们解决什么实际问题?

在日常生活中,你可能已经在不知不觉中使用了这个技术:
- 📱 手机App
- 🎮 游戏
- 🛒 网购
- 📺 视频推荐

让我们一起探索这个技术背后的原理!

### 🎯 为什么需要这个技术?

**问题:** 传统方法有什么局限?
- 效率低?
- 准确率低?
- 不能处理复杂情况?

**解决:** 这个技术如何改进?
- 提高效率?
- 提高准确率?
- 处理复杂情况?

### 📚 循序渐进学习

**第一步: 理解问题** (你现在在这里)
- 为什么需要这个技术?
- 它解决什么问题?

**第二步: 学习原理** (接下来)
- 这个技术如何工作?
- 核心思想是什么?

**第三步: 实际应用** (最后)
- 如何应用到实际项目?
- 如何解决实际问题?

---

## 🎯 本节课你将学会

- ✅ 理解核心概念和原理
- ✅ 掌握实际代码实现
- ✅ 知道如何应用到实际项目
- ✅ 理解这个技术解决什么问题

## 💡 学习建议

1. **先理解"为什么"** - 这个技术解决什么实际问题?
2. **再学习"是什么"** - 这个技术的原理是什么?
3. **最后掌握"怎么做"** - 如何用代码实现?
4. **动手实践** - 运行代码,修改参数,观察结果

---



# 使用购买GPU

**分类:** 高级主题

**🎯 让我们从实际问题出发**

---


## 💭 开始之前:想想这个问题

学习 **使用购买GPU** 能帮我们解决什么实际问题?

在日常生活中,你可能已经在不知不觉中使用了这个技术:
- 📱 手机App
- 🎮 游戏
- 🛒 网购
- 📺 视频推荐

让我们一起探索这个技术背后的原理!

### 🎯 为什么需要这个技术?

**问题:** 传统方法有什么局限?
- 效率低?
- 准确率低?
- 不能处理复杂情况?

**解决:** 这个技术如何改进?
- 提高效率?
- 提高准确率?
- 处理复杂情况?

### 📚 循序渐进学习

**第一步: 理解问题** (你现在在这里)
- 为什么需要这个技术?
- 它解决什么问题?

**第二步: 学习原理** (接下来)
- 这个技术如何工作?
- 核心思想是什么?

**第三步: 实际应用** (最后)
- 如何应用到实际项目?
- 如何解决实际问题?

---

## 🎯 本节课你将学会

- ✅ 理解核心概念和原理
- ✅ 掌握实际代码实现
- ✅ 知道如何应用到实际项目
- ✅ 理解这个技术解决什么问题

## 💡 学习建议

1. **先理解"为什么"** - 这个技术解决什么实际问题?
2. **再学习"是什么"** - 这个技术的原理是什么?
3. **最后掌握"怎么做"** - 如何用代码实现?
4. **动手实践** - 运行代码,修改参数,观察结果

---



# 使用购买GPU

**分类:** 高级主题

**🎯 让我们从实际问题出发**

---


## 💭 开始之前,想想这个问题

学习 **使用购买GPU** 能帮我们解决什么实际问题?

在日常生活中,你可能已经在不知不觉中使用了这个技术:
- 📱 手机App
- 🎮 游戏
- 🛒 网购
- 📺 视频推荐

让我们一起探索这个技术背后的原理!

---

## 🎯 本节课你将学会

- ✅ 理解核心概念和原理
- ✅ 掌握实际代码实现
- ✅ 知道如何应用到实际项目
- ✅ 理解这个技术解决什么问题

## 💡 学习建议

1. **先理解"为什么"** - 这个技术解决什么实际问题?
2. **再学习"是什么"** - 这个技术的原理是什么?
3. **最后掌握"怎么做"** - 如何用代码实现?
4. **动手实践** - 运行代码,修改参数,观察结果

---



# 1. 确认GPU

In [1]:
!nvidia-smi

Sat Apr 30 18:03:10 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 471.35       Driver Version: 471.35       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   57C    P5    27W /  N/A |   2535MiB / 16384MiB |     10%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
from torch import nn

torch.device('cpu'), torch.cuda.device('cuda'), torch.cuda.device('cuda:1')

(device(type='cpu'),
 <torch.cuda.device at 0x2a59c8b2588>)

In [3]:
print(torch.cuda.device_count())

1


In [4]:
def try_gpu(i=0):
    """如果存在，则返回gpu(i)，否则返回gpu"""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():
    """返回所有可用的GPU，如果没有GPU，则返回[cpu(),]。"""
    devices = [torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())]      
    return devices if devices else [torch.device('cpu')]
                    
print(try_gpu())
print(try_gpu(10))
print(try_all_gpus())

cuda:0
cpu
[device(type='cuda', index=0)]


In [5]:
# 查询张量所在设备
X = torch.tensor([1,2,3])
print(X.device) # 默认在CPU内存上

cpu


In [6]:
# 存储在GPU上
X = torch.ones(2,3,device=try_gpu())
X 

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [7]:
# 在第二个GPU上创建一个随即张量
Y = torch.rand(2,3,device=try_gpu(1))
print(Y.device) # 没有1号GPU，则放到CPU上
Y

cpu


tensor([[0.3045, 0.4398, 0.9162],
        [0.5351, 0.1256, 0.8916]])

In [8]:
# 要计算X+Y，我们需要决定在哪里执行这个操作
Z = X.cuda(0) # X+Y必须X和Y都在同一个GPU上
print(X)
print(Z)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [9]:
Y = torch.rand(2,3,device=try_gpu(0))
Y + Z
Z.cuda(0) is Z # 如果变量在0号GPU时，就返回True

True

In [10]:
# 神经网络与GPU
net = nn.Sequential(nn.Linear(3,1)) # 创建神经网络时已经把权重初始化好了
net = net.to(device=try_gpu()) # 把所有参数在0号GPU上拷贝一份
X = torch.ones(2,3,device=try_gpu()) # X 在0号GPU上
net(X) # 所以前项运算所有元素都在0号GPU上运行

tensor([[0.7668],
        [0.7668]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [11]:
# 确认模型参数存储在同一个GPU上
net[0].weight.data.device

device(type='cuda', index=0)

---


### 🌍 实际应用场景

1. **手机拍照优化**
   - 场景: iPhone、华为等手机的AI拍照
   - 应用: 自动识别场景(人像/风景/美食),优化参数
   - 效果: 随手一拍就是大片
   - 案例: 华为P系列手机的AI摄影获得多项大奖

2. **智能家居**
   - 场景: 小米、华为的智能家居系统
   - 应用: 学习你的生活习惯,自动调节空调、灯光
   - 效果: 回家前自动开空调,睡觉时自动关灯
   - 案例: 小米IoT平台连接设备超5亿台

3. **在线教育**
   - 场景: 作业帮、猿辅导的拍照搜题
   - 应用: 拍下题目,AI自动识别并给出解答
   - 效果: 秒出答案和详细解析
   - 案例: 作业帮月活用户超1.7亿

4. **健康监测**
   - 场景: Apple Watch、小米手环的健康监测
   - 应用: 分析心率、睡眠、运动数据
   - 效果: 及时发现健康异常,提醒就医
   - 案例: Apple Watch曾多次救人性命

5. **智能翻译**
   - 场景: 有道翻译、Google翻译
   - 应用: 实时翻译语音和文字
   - 效果: 出国旅游不再担心语言不通
   - 案例: 有道翻译支持100+种语言互译

---



---


### 🌍 实际应用场景

1. **手机拍照优化**
   - 场景: iPhone、华为等手机的AI拍照
   - 应用: 自动识别场景(人像/风景/美食),优化参数
   - 效果: 随手一拍就是大片
   - 案例: 华为P系列手机的AI摄影获得多项大奖

2. **智能家居**
   - 场景: 小米、华为的智能家居系统
   - 应用: 学习你的生活习惯,自动调节空调、灯光
   - 效果: 回家前自动开空调,睡觉时自动关灯
   - 案例: 小米IoT平台连接设备超5亿台

3. **在线教育**
   - 场景: 作业帮、猿辅导的拍照搜题
   - 应用: 拍下题目,AI自动识别并给出解答
   - 效果: 秒出答案和详细解析
   - 案例: 作业帮月活用户超1.7亿

4. **健康监测**
   - 场景: Apple Watch、小米手环的健康监测
   - 应用: 分析心率、睡眠、运动数据
   - 效果: 及时发现健康异常,提醒就医
   - 案例: Apple Watch曾多次救人性命

5. **智能翻译**
   - 场景: 有道翻译、Google翻译
   - 应用: 实时翻译语音和文字
   - 效果: 出国旅游不再担心语言不通
   - 案例: 有道翻译支持100+种语言互译

---



---

## 📚 本节小结

恭喜你完成了本节学习!让我们回顾一下:

### ✅ 你学到了什么?
- 请在这里写下你的收获...

### 🤔 还有疑问?
- 请记录下你不理解的地方...

### 🚀 下一步
- 继续学习相关主题
- 尝试做一些练习题
- 应用到实际项目中

---

**记住:** 学习是一个循序渐进的过程,不要着急,慢慢来! 💪
